### ISSUE TITLE
Unable to 'generate 3D model' with turbid object 

### ISSUE THREAD

**Issue by JulFrey** [jianboqi/lessrt#3]
If I create a new simulation and add a sphere under 'define objects' and set it to a turbid medium, its not possible to run 'generate 3d model' any more. The console prints the following error:
`INFO: Generating terrain...
INFO: Terrain generated.
Traceback (most recent call last):
  File "C:\Program Files\LESS\app\bin\scripts\Lesspy\less.py", line 79, in <module>
    SceneGenerate.generate_objects_file(cfgfile)
  File "C:\Program Files\LESS\app\bin\scripts\Lesspy\SceneGenerate.py", line 1732, in generate_objects_file
    xm = objdoc.toprettyxml()
  File "C:\Program Files\LESS\app\bin\python\lib\xml\dom\minidom.py", line 60, in toprettyxml
    self.writexml(writer, "", indent, newl, encoding, standalone)
  File "C:\Program Files\LESS\app\bin\python\lib\xml\dom\minidom.py", line 1826, in writexml
    node.writexml(writer, indent, addindent, newl)
  File "C:\Program Files\LESS\app\bin\python\lib\xml\dom\minidom.py", line 895, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Program Files\LESS\app\bin\python\lib\xml\dom\minidom.py", line 895, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Program Files\LESS\app\bin\python\lib\xml\dom\minidom.py", line 895, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  [Previous line repeated 1 more time]
  File "C:\Program Files\LESS\app\bin\python\lib\xml\dom\minidom.py", line 884, in writexml
    _write_data(writer, attrs[a_name].value)
  File "C:\Program Files\LESS\app\bin\python\lib\xml\dom\minidom.py", line 306, in _write_data
    data = data.replace("&", "&amp;").replace("<", "&lt;"). \
AttributeError: 'int' object has no attribute 'replace'
`
![grafik](https://github.com/user-attachments/assets/9b0340f2-6fa8-4c12-844b-879e6f6caa64)

Any Idea what could be wrong or needs to be set?

**Comment by jianboqi** [comment]
Hi, this is simply a small bug in the version of 04-26 because of writing integer to xml file. This has been fixed in the following version, you can use the latest version of 7.19 that I just uploaded, which has been tested OK. https://drive.google.com/file/d/1o1MW2oKIWsX6DUZ7Ut-4r2CitOTxnhE0/view?usp=sharing

**Comment by JulFrey** [comment]
Thank you very much for the fast and helpful reply. This solved the problem.
